#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use TinyPNG\Console\Commands\ApiKey\GenerateCommand;
use TinyPNG\Console\Commands\ApiKey\ConfigureCommand;
use TinyPNG\Console\Commands\ReduceCommand;

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}
$app = new Application('TinyPNG Console', '1.1.0');
$app->add(new ReduceCommand());
$app->add(new ConfigureCommand());
$app->add(new GenerateCommand());
$app->run();